<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Skills Portfolio Program - Statistical Modelling: Predicting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data_skills_logo_2.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Skills Portfolio Program</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./intro.html" rel="" target="">
 <span class="menu-text">What is the DSP Program?</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./handbookIntro.html" rel="" target="">
 <span class="menu-text">The DSP Program Handbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./feedback.html" rel="" target="">
 <span class="menu-text">Feedback</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#predicting" id="toc-predicting" class="nav-link active" data-scroll-target="#predicting"><span class="header-section-number">1</span> Predicting</a>
  <ul class="collapse">
  <li><a href="#the-process" id="toc-the-process" class="nav-link" data-scroll-target="#the-process"><span class="header-section-number">1.1</span> The process</a>
  <ul class="collapse">
  <li><a href="#step-zero-consider-your-prediction-limits" id="toc-step-zero-consider-your-prediction-limits" class="nav-link" data-scroll-target="#step-zero-consider-your-prediction-limits">Step Zero: consider your prediction limits</a></li>
  <li><a href="#step-one-define-the-predictor-values-for-your-response-prediction" id="toc-step-one-define-the-predictor-values-for-your-response-prediction" class="nav-link" data-scroll-target="#step-one-define-the-predictor-values-for-your-response-prediction">Step One: Define the predictor values for your response prediction</a></li>
  <li><a href="#step-two-make-your-response-prediction" id="toc-step-two-make-your-response-prediction" class="nav-link" data-scroll-target="#step-two-make-your-response-prediction">Step Two: Make your response prediction</a></li>
  </ul></li>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples"><span class="header-section-number">1.2</span> Examples</a>
  <ul class="collapse">
  <li><a href="#example-3-resp3-cont4-1" id="toc-example-3-resp3-cont4-1" class="nav-link" data-scroll-target="#example-3-resp3-cont4-1">Example 3: Resp3 ~ Cont4 + 1</a></li>
  <li><a href="#example-4-resp4-cat5-cont6-cat5cont6-1" id="toc-example-4-resp4-cat5-cont6-cat5cont6-1" class="nav-link" data-scroll-target="#example-4-resp4-cat5-cont6-cat5cont6-1">Example 4: Resp4 ~ Cat5 + Cont6 + Cat5:Cont6 + 1</a></li>
  </ul></li>
  <li><a href="#inverse-predicting-for-models-with-a-binomial-error-distribution-assumption" id="toc-inverse-predicting-for-models-with-a-binomial-error-distribution-assumption" class="nav-link" data-scroll-target="#inverse-predicting-for-models-with-a-binomial-error-distribution-assumption"><span class="header-section-number">1.3</span> Inverse predicting for models with a binomial error distribution assumption</a></li>
  <li><a href="#up-next" id="toc-up-next" class="nav-link" data-scroll-target="#up-next"><span class="header-section-number">1.4</span> Up next</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistical Modelling: Predicting</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In this chapter you will learn:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>how to use your statistical model to make a prediction</li>
</ul>
</div>
</div>
</div>
<section id="predicting" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Predicting</h1>
<p>One of the motivations we discussed <a href="./handbookSMIntro.html">motivations for statistical modelling</a> was that models help us to make quantitative predictions about the system which we are studying.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Now that you have your best-specified model, you may want to use it to make a response prediction<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, e.g.&nbsp;“what would I expect the value of my response to be at a different value of my predictor?”</p>
<div class="alert alert-warning">
<p>The predicting process outlined here is similar regardless of your model structure (e.g.&nbsp;error distribution assumption). You can use the same process for models of any structure.</p>
</div>
<section id="the-process" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-process"><span class="header-section-number">1.1</span> The process</h2>
<p>Here we will go through the steps involved in using your model to make a prediction about your response, including (most importantly):</p>
<section id="step-zero-consider-your-prediction-limits" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-zero-consider-your-prediction-limits">Step Zero: consider your prediction limits</h3>
<p>Before using your model to make a prediction, ask yourself: is it even logical to make this prediction?</p>
<p>Things you should consider:</p>
<ul>
<li><strong>do I have a numeric predictor in my best-specified model?</strong></li>
</ul>
<p>If you have only categorical predictors in your model, you can not use your model to make a prediction outside the categories already in your model.</p>
<p>Let’s bring in our Example 1 from the last chapter on Reporting to illustrate the prediction limits of models with only categorical predictors:</p>
<p><code>Resp1 ~ Cat1</code></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here you can see the modelled <code>Resp1</code> when <code>Cat1</code> is Sp1, Sp2 or Sp3. You are not able to make a prediction for <code>Cat1 = Sp4</code> or <code>Cat1 = Sp63</code>. This is limits of prediction limit when you have a categorical predictor. You are able to report the variability in <code>Resp1</code> that is explained by <code>Cat1</code> - this can give you an idea for how much <code>Resp1</code> might vary if you study a new species.</p>
<ul>
<li><strong>Can I assume that my model assumptions will hold under my prediction conditions?</strong></li>
</ul>
<p>By using your model to make a prediction, you are assuming that the same processes that govern the relationship(s) between your predictor(s) and response will hold at the new value of your predictor. For example, you might have used a linear shape assumption that was appropriate for modelling how growth varies due to temperature for your data, but now you want to estimate growth at an even higher temperature than you tested. Is this appropriate? Would it be possible that temperature has exceeded a tolerance limit and that growth starts to respond non-linearly with temperature?</p>
<p><img src="./predLimitsTPC.png" width="700px"></p>
<p>As you can see, you need to consider prediction limits particularly when you are making a prediction using a value of your predictor <em>outside</em> the range of your predictor used to fit your model.</p>
<p>You also need to consider prediction limits when you are wanting to predict your response at a future time or different location.</p>
<p>In all cases: Think about the mechanisms underlying your hypothesis to consider if they are likely to be the same under your prediction conditions. This will help you decide if making a prediction is appropriate.</p>
</section>
<section id="step-one-define-the-predictor-values-for-your-response-prediction" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-one-define-the-predictor-values-for-your-response-prediction">Step One: Define the predictor values for your response prediction</h3>
<p>The first step in using your model to make a response prediction is to define the values of your predictor(s) at which you want to make the response prediction. Note that you need to define a value for <em>each</em> of the predictors in your model, the defined values need to be in a data frame, and the columns should be given the same names as your predictors.</p>
</section>
<section id="step-two-make-your-response-prediction" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="step-two-make-your-response-prediction">Step Two: Make your response prediction</h3>
<p>You can use the <code>predict()</code><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> function to predict the value of your response.</p>
</section>
</section>
<section id="examples" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="examples"><span class="header-section-number">1.2</span> Examples</h2>
<p>Note that Example 1 (<code>Resp1 ~ Cat1</code>) and Example 2 (<code>Resp2 ~ Cat2 + Cat3 + Cat2:Cat3 + 1</code>) from the previous chapter on Reporting only contained categorical predictors, so we will not explore them further here.</p>
<p>Examples 3 (<code>Resp3 ~ Cont4 + 1</code>) and 4 (<code>Resp4 ~ Cat5 + Cont6 + Cat5:Cont6 + 1</code>) each contain a numeric predictor, so we will use those here as an example of how to use your models to make a prediction of your response.</p>
<section id="example-3-resp3-cont4-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="example-3-resp3-cont4-1">Example 3: Resp3 ~ Cont4 + 1</h3>
<p>Here’s a reminder of Example 3 (<code>Resp3 ~ Cont4 + 1</code>):</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="what-is-the-predicted-response-of-resp3-when-cont4-30" class="level4">
<h4 class="anchored" data-anchor-id="what-is-the-predicted-response-of-resp3-when-cont4-30">What is the predicted response of <code>Resp3</code> when <code>Cont4 = 30</code>?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step One: Define the predictor values for your response prediction</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>forPred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Cont4 =</span> <span class="dv">30</span>) <span class="co"># the values of my predictor at which I want a response prediction</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Step Two: Make your response prediction</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>myPred<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod3, <span class="co"># the model</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forPred, <span class="co"># the predictor values</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod3)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="do">### This can be added to our forPred data frame as:</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>forPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Cont4      Fit    Lower    Upper
1    30 7574.809 6980.293 8169.325</code></pre>
</div>
</div>
<p>Note that you get the response prediction in <code>forPred$Fit</code> = 7575 units and an estimate of uncertainty around this prediction as the 95% confidence intervals (6980 to 8169 units).</p>
<p>Note that you can also use the <a href="https://strengejacke.github.io/ggeffects/">ggeffects package</a> to make these predictions.</p>
<p>So the value of <code>Resp3</code> when <code>Cont4 = 30 units</code> is 7575 units (95% confidence intervals: 6980 to 8169 units).</p>
<p>You can add this to your plot with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up your predictors for the visualized fit</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>forCont4<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(myDat3<span class="sc">$</span>Cont4), <span class="at">to =</span> <span class="fu">max</span>(myDat3<span class="sc">$</span>Cont4), <span class="at">by =</span> <span class="dv">1</span>)<span class="co"># a sequence of numbers in your numeric predictor range</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame with your predictors</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>forVis<span class="ot">&lt;-</span><span class="fu">expand.grid</span>(<span class="at">Cont4 =</span> forCont4) <span class="co"># expand.grid() function makes sure you have all combinations of predictors.  </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Get your model fit estimates at each value of your predictors</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>modFit<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod3, <span class="co"># the model</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forVis, <span class="co"># the predictor values</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod3)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># load ggplot2 library</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># start ggplot</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> myDat3, <span class="co"># add observations to your plot</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Resp3)) <span class="sc">+</span> <span class="co"># control position of data points so they are easier to see on the plot</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add the modelled fit to your plot</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Fit),</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span> <span class="co"># control thickness of line</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (upper line)</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Upper),</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.8</span>, <span class="co"># control thickness of line</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (lower line)</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Lower),</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.8</span>, <span class="co"># control thickness of line</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>  <span class="do">### NEW!  Adding your response prediction to the plot:</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Fit), <span class="co"># coordinates of prediction</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"red"</span>, <span class="co"># change point colour</span></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="co"># change point size</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>  <span class="do">### NEW!  Adding errorbars for your response prediction to the plot:</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">ymax =</span> Upper, <span class="at">ymin =</span> Lower), <span class="co"># coordinates of prediction</span></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>             <span class="at">width =</span> <span class="dv">1</span>, <span class="co"># the width of the error bars</span></span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span> <span class="co"># change point colour</span></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Resp3, (units)"</span>) <span class="sc">+</span> <span class="co"># change y-axis label</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Cont4, (units)"</span>) <span class="sc">+</span> <span class="co"># change x-axis label</span></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="co"># change ggplot theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="what-are-the-predicted-responses-of-resp3-when-cont4-9-and-cont4-22" class="level4">
<h4 class="anchored" data-anchor-id="what-are-the-predicted-responses-of-resp3-when-cont4-9-and-cont4-22">What are the predicted responses of <code>Resp3</code> when <code>Cont4 = 9</code> and <code>Cont4 = 22</code>?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step One: Define the predictor values for your response prediction</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>forPred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Cont4 =</span> <span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">22</span>)) <span class="co"># the values of my predictor at which I want a response prediction</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Step Two: Make your response prediction</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>myPred<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod3, <span class="co"># the model</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forPred, <span class="co"># the predictor values</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod3)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="do">### This can be added to our forPred data frame as:</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>forPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Cont4      Fit    Lower    Upper
1     9 2113.604 1951.820 2275.387
2    22 5494.350 5114.867 5873.832</code></pre>
</div>
</div>
<p>Note that you now get two predictions, one for <code>Cont4 = 9</code> and one for <code>Cont4 = 22</code>:</p>
<ul>
<li><p>The value of <code>Resp3</code> when <code>Cont4 = 9 units</code> is 2114 units (95% confidence intervals: 1952 to 2275 units).</p></li>
<li><p>The value of <code>Resp3</code> when <code>Cont4 = 22 units</code> is 5494 units (95% confidence intervals: 5115 to 5874 units).</p></li>
</ul>
<p>You can add this to your plot with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up your predictors for the visualized fit</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>forCont4<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(myDat3<span class="sc">$</span>Cont4), <span class="at">to =</span> <span class="fu">max</span>(myDat3<span class="sc">$</span>Cont4), <span class="at">by =</span> <span class="dv">1</span>)<span class="co"># a sequence of numbers in your numeric predictor range</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame with your predictors</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>forVis<span class="ot">&lt;-</span><span class="fu">expand.grid</span>(<span class="at">Cont4 =</span> forCont4) <span class="co"># expand.grid() function makes sure you have all combinations of predictors.  </span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Get your model fit estimates at each value of your predictors</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>modFit<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod3, <span class="co"># the model</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forVis, <span class="co"># the predictor values</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod3)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># load ggplot2 library</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># start ggplot</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> myDat3, <span class="co"># add observations to your plot</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Resp3)) <span class="sc">+</span> <span class="co"># control position of data points so they are easier to see on the plot</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add the modelled fit to your plot</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Fit),</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span> <span class="co"># control thickness of line</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (upper line)</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Upper),</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.8</span>, <span class="co"># control thickness of line</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (lower line)</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Lower),</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.8</span>, <span class="co"># control thickness of line</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>  <span class="do">### NEW!  Adding your response prediction to the plot:</span></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">y =</span> Fit), <span class="co"># coordinates of prediction</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"orange"</span>, <span class="co"># change point colour</span></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="co"># change point size</span></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>  <span class="do">### NEW!  Adding errorbars for your response prediction to the plot:</span></span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont4, <span class="at">ymax =</span> Upper, <span class="at">ymin =</span> Lower), <span class="co"># coordinates of prediction</span></span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>             <span class="at">width =</span> <span class="dv">1</span>, <span class="co"># the width of the error bars</span></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"orange"</span>) <span class="sc">+</span> <span class="co"># change point colour</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Resp3, (units)"</span>) <span class="sc">+</span> <span class="co"># change y-axis label</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Cont4, (units)"</span>) <span class="sc">+</span> <span class="co"># change x-axis label</span></span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="co"># change ggplot theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="example-4-resp4-cat5-cont6-cat5cont6-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="example-4-resp4-cat5-cont6-cat5cont6-1">Example 4: Resp4 ~ Cat5 + Cont6 + Cat5:Cont6 + 1</h3>
<p>Here’s a reminder of Example 4 (<code>Resp4 ~ Cat5 + Cont6 + Cat5:Cont6 + 1</code>):</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="example-what-is-the-predicted-response-of-resp4-when-cont6-800-for-cat5-urban" class="level4">
<h4 class="anchored" data-anchor-id="example-what-is-the-predicted-response-of-resp4-when-cont6-800-for-cat5-urban">Example: What is the predicted response of <code>Resp4</code> when <code>Cont6 = 800</code> for <code>Cat5 = Urban</code>?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step One: Define the predictor values for your response prediction</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>forPred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Cont6 =</span> <span class="dv">800</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">Cat5 =</span> <span class="st">"Urban"</span>) <span class="co"># the values of my predictor at which I want a response prediction</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Step Two: Make your response prediction</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>myPred<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod4, <span class="co"># the model</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forPred, <span class="co"># the predictor values</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod4)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="do">### This can be added to our forPred data frame as:</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>forPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Cont6  Cat5      Fit    Lower    Upper
1   800 Urban 107.8597 105.4153 110.3041</code></pre>
</div>
</div>
<p>So the value of <code>Resp4</code> when <code>Cont6 = 800</code> units for <code>Cat5 = Urban</code> is 107.9 units (95% confidence intervals: 105.4 to 110.3 units).</p>
<p>You can add this to your plot with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### i) choosing the values of your predictors at which to make a prediction</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up your predictors for the visualized fit</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>forCat5<span class="ot">&lt;-</span><span class="fu">unique</span>(myDat4<span class="sc">$</span>Cat5) <span class="co"># all levels of your categorical predictor</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>forCont6<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(myDat4<span class="sc">$</span>Cont6), <span class="at">to =</span> <span class="fu">max</span>(myDat4<span class="sc">$</span>Cont6), <span class="at">by =</span> <span class="dv">1</span>)<span class="co"># a sequence of numbers in your numeric predictor range</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame with your predictors</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>forVis<span class="ot">&lt;-</span><span class="fu">expand.grid</span>(<span class="at">Cat5 =</span> Cat5, <span class="at">Cont6 =</span> forCont6) <span class="co"># expand.grid() function makes sure you have all combinations of predictors.  </span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="do">#### ii) using `predict()` to use your model to estimate your response variable at those values of your predictor</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Get your model fit estimates at each value of your predictors</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>modFit<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod4, <span class="co"># the model</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forVis, <span class="co"># the predictor values</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod4)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="do">#### iii) use the model estimates to plot your model fit</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># load ggplot2 library</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># start ggplot</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> myDat4, <span class="co"># add observations to your plot</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Resp4, <span class="at">col =</span> Cat5)) <span class="sc">+</span> <span class="co"># control position of data points so they are easier to see on the plot</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add the modelled fit to your plot</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Fit, <span class="at">col =</span> Cat5),</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span> <span class="co"># control thickness of line</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (upper line)</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Upper, <span class="at">col =</span> Cat5),</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.4</span>, <span class="co"># control thickness of line</span></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (lower line)</span></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Lower, <span class="at">col =</span> Cat5),</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.4</span>, <span class="co"># control thickness of line</span></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>    <span class="do">### NEW!  Adding your response prediction to the plot:</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Fit, <span class="at">col =</span> Cat5), <span class="co"># coordinates of prediction</span></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>             <span class="co">#col = "black", # change point colour</span></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="co"># change point size</span></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>  <span class="do">### NEW!  Adding errorbars for your response prediction to the plot:</span></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">ymax =</span> Upper, <span class="at">ymin =</span> Lower,  <span class="at">col =</span> Cat5), <span class="co"># coordinates of prediction</span></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>             <span class="at">width =</span> <span class="dv">20</span>, <span class="co"># the width of the error bars</span></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>             <span class="co">#col = "black"</span></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>             ) <span class="sc">+</span> <span class="co"># change point colour</span></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Resp4, (units)"</span>) <span class="sc">+</span> <span class="co"># change y-axis label</span></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Cont6, (units)"</span>) <span class="sc">+</span> <span class="co"># change x-axis label</span></span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">"Cat5, (units)"</span>, <span class="at">col=</span><span class="st">"Cat5, (units)"</span>) <span class="sc">+</span> <span class="co"># change legend title</span></span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="co"># change ggplot theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="example-what-is-the-predicted-response-of-resp4-when-cont6-800-for-both-cat5-urban-and-cat5-wild" class="level4">
<h4 class="anchored" data-anchor-id="example-what-is-the-predicted-response-of-resp4-when-cont6-800-for-both-cat5-urban-and-cat5-wild">Example: What is the predicted response of <code>Resp4</code> when <code>Cont6 = 800</code> for both <code>Cat5 = Urban</code> and <code>Cat5 = Wild</code>?</h4>
<p>Note the extra step with <code>expand.grid()</code> that allows you to quickly set up your predictor values for the prediction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step One: Define the predictor values for your response prediction</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>forCat5 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Urban"</span>, <span class="st">"Wild"</span>) <span class="co"># values of Cat5 for predictions</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>forCont6 <span class="ot">&lt;-</span> <span class="dv">800</span> <span class="co"># value of Cont6 for prediction</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>forPred <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Cat5 =</span> forCat5, <span class="at">Cont6 =</span> forCont6) <span class="co"># expand.grid() function makes sure you have all combinations of predictors.</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Step Two: Make your response prediction</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>myPred<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod4, <span class="co"># the model</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forPred, <span class="co"># the predictor values</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod4)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="do">### This can be added to our forPred data frame as:</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>forPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cat5 Cont6      Fit    Lower    Upper
1 Urban   800 107.8597 105.4153 110.3041
2  Wild   800 119.8214 117.0121 122.6307</code></pre>
</div>
</div>
<p>So</p>
<ul>
<li><p>the value of <code>Resp4</code> when <code>Cont6 = 800</code> units is both <code>Cat5 = Urban</code> is 107.9 units (95% confidence intervals: 105.4 to 110.3 units).</p></li>
<li><p>the value of <code>Resp4</code> when <code>Cont6 = 800</code> units is both <code>Cat5 = Wild</code> is 119.8 units (95% confidence intervals: 117 to 122.6 units).</p></li>
</ul>
<p>You can add this to your plot with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### i) choosing the values of your predictors at which to make a prediction</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up your predictors for the visualized fit</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>forCat5<span class="ot">&lt;-</span><span class="fu">unique</span>(myDat4<span class="sc">$</span>Cat5) <span class="co"># all levels of your categorical predictor</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>forCont6<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(myDat4<span class="sc">$</span>Cont6), <span class="at">to =</span> <span class="fu">max</span>(myDat4<span class="sc">$</span>Cont6), <span class="at">by =</span> <span class="dv">1</span>)<span class="co"># a sequence of numbers in your numeric predictor range</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame with your predictors</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>forVis<span class="ot">&lt;-</span><span class="fu">expand.grid</span>(<span class="at">Cat5 =</span> forCat5, <span class="at">Cont6 =</span> forCont6) <span class="co"># expand.grid() function makes sure you have all combinations of predictors.  </span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="do">#### ii) using `predict()` to use your model to estimate your response variable at those values of your predictor</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Get your model fit estimates at each value of your predictors</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>modFit<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod4, <span class="co"># the model</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forVis, <span class="co"># the predictor values</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod4)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>forVis<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(modFit<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>modFit<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="do">#### iii) use the model estimates to plot your model fit</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># load ggplot2 library</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> <span class="co"># start ggplot</span></span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> myDat4, <span class="co"># add observations to your plot</span></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Resp4, <span class="at">col =</span> Cat5)) <span class="sc">+</span> <span class="co"># control position of data points so they are easier to see on the plot</span></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add the modelled fit to your plot</span></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Fit, <span class="at">col =</span> Cat5),</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span> <span class="co"># control thickness of line</span></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (upper line)</span></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Upper, <span class="at">col =</span> Cat5),</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.4</span>, <span class="co"># control thickness of line</span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="at">data =</span> forVis, <span class="co"># add uncertainty to your plot (lower line)</span></span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Lower, <span class="at">col =</span> Cat5),</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.4</span>, <span class="co"># control thickness of line</span></span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="co"># control style of line</span></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>    <span class="do">### NEW!  Adding your response prediction to the plot:</span></span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">y =</span> Fit, <span class="at">col =</span> Cat5), <span class="co"># coordinates of prediction</span></span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>             <span class="co">#col = "black", # change point colour</span></span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="co"># change point size</span></span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>  <span class="do">### NEW!  Adding errorbars for your response prediction to the plot:</span></span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> forPred, <span class="co"># prediction data frame</span></span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>             <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Cont6, <span class="at">ymax =</span> Upper, <span class="at">ymin =</span> Lower,  <span class="at">col =</span> Cat5), <span class="co"># coordinates of prediction</span></span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>             <span class="at">width =</span> <span class="dv">20</span>, <span class="co"># the width of the error bars</span></span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>             <span class="co">#col = "black"</span></span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>             ) <span class="sc">+</span> <span class="co"># change point colour</span></span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Resp4, (units)"</span>) <span class="sc">+</span> <span class="co"># change y-axis label</span></span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Cont6, (units)"</span>) <span class="sc">+</span> <span class="co"># change x-axis label</span></span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">"Cat5, (units)"</span>, <span class="at">col=</span><span class="st">"Cat5, (units)"</span>) <span class="sc">+</span> <span class="co"># change legend title</span></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="co"># change ggplot theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="inverse-predicting-for-models-with-a-binomial-error-distribution-assumption" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="inverse-predicting-for-models-with-a-binomial-error-distribution-assumption"><span class="header-section-number">1.3</span> Inverse predicting for models with a binomial error distribution assumption</h2>
<p>While the process (and code) above is <em>identical</em> regardless of your error distribution assumption, there is a second type of predicting one often uses when one has a model with a binomial error distribution assumption<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>Here, you are “inverse predicting” to predict the value of your <em>predictor</em> that will lead to a certain probability of your response being 1.</p>
<p>For example, you might want to know the amount of a toxin (your predictor) that leads to a 25% probability of dying<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>, or the age (your predictor) at which a fish has a 50% probability of being mature<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
<p>One method to do this would be to predict your response at values of your predictor in high enough resolution so that you can pick out the appropriate predictor value. Here is an example where you want to know the value of <code>Cont4</code> that will give a 75% probability of <code>Resp3.b</code> being 1, given your bestmod3.b of <code>Resp3.b ~ Cont4 + 1</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>forCont4<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(myDat3.b<span class="sc">$</span>Cont4), <span class="at">to =</span> <span class="fu">max</span>(myDat3.b<span class="sc">$</span>Cont4), <span class="at">by =</span> <span class="fl">0.01</span>)<span class="co"># a sequence of numbers in your numeric predictor range, notice that you are using a very high resolution series of your predictor here.</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>forPred <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Cont4 =</span> forCont4) <span class="co"># expand.grid() function makes sure you have all combinations of predictors.</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Step Two: Make your response prediction</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>myPred<span class="ot">&lt;-</span><span class="fu">predict</span>(bestMod3.b, <span class="co"># the model</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> forPred, <span class="co"># the predictor values</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"link"</span>, <span class="co"># here, make the predictions on the link scale and we'll translate the back below</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit =</span> <span class="cn">TRUE</span>) <span class="co"># include uncertainty estimate</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>ilink <span class="ot">&lt;-</span> <span class="fu">family</span>(bestMod3.b)<span class="sc">$</span>linkinv <span class="co"># get the conversion (inverse link) from the model to translate back to the response scale</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="do">### This can be added to our forPred data frame as:</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Fit<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit) <span class="co"># add your fit to the data frame</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Lower<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>forPred<span class="sc">$</span>Upper<span class="ot">&lt;-</span><span class="fu">ilink</span>(myPred<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>myPred<span class="sc">$</span>se.fit) <span class="co"># add your uncertainty to the data frame, 95% confidence intervals</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>myPredDF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Cont4 =</span> forCont4,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Fit =</span> forPred<span class="sc">$</span>Fit,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Lower =</span> forPred<span class="sc">$</span>Lower,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Upper =</span> forPred<span class="sc">$</span>Upper)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>myPredDF<span class="sc">$</span>Diff <span class="ot">&lt;-</span> <span class="fu">abs</span>(myPred<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">0.75</span>)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>myInvPred <span class="ot">&lt;-</span> myPredDF[<span class="fu">which</span>(myPredDF<span class="sc">$</span>Diff <span class="sc">==</span> <span class="fu">min</span>(myPredDF<span class="sc">$</span>Diff)),]</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>myInvPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Cont4       Fit     Lower     Upper        Diff
5094 81.9691 0.6790692 0.5899505 0.7568036 0.000502456</code></pre>
</div>
</div>
<p>The estimate of <code>Cont4</code> that leads to a 75% probability of <code>Resp3.b</code> being 1 is 0.7 units (95% confidence intervals: 0.59 to 0.76.</p>
<p>As you can see, this is a bit tedious. Another method would be to make a function yourself based on your statistical model equation and coefficients:</p>
<p>Note that your statistical model (GLM) with a binomial error distribution is:</p>
<p><span class="math display">\[ log_n(\frac{p}{1-p}) = \beta_0 + \beta_1 \cdot x \]</span></p>
<p>where <span class="math inline">\(log_n(\frac{p}{1-p})\)</span> is the logit function of the odds (see the <a href="./DSPPH_SM_Reporting.html">Reporting</a> section for more), <span class="math inline">\(p\)</span> is the probability at which you want a value of your predictor, <span class="math inline">\(x\)</span> is the value of your predictor, <span class="math inline">\(\beta_0\)</span> is your modelled intercept, and <span class="math inline">\(\beta_1\)</span> is your modelled slope (effect of your numeric predictor).</p>
<p>Inverse predicting means finding the value of <span class="math inline">\(x\)</span> that gives you a particular value of <span class="math inline">\(p\)</span>. So we need to solve our equation for <span class="math inline">\(x\)</span>:</p>
<p><span class="math display">\[\begin{align}
log_n(\frac{p}{1-p}) &amp;= \beta_0 + \beta_1 \cdot x\\[1em]

log_n(\frac{p}{1-p}) - \beta_0 &amp;= \beta_1 \cdot x\\[1em]

\frac{log_n(\frac{p}{1-p}) - \beta_0}{\beta_1} &amp;=  x\\[1em]

\end{align}\]</span></p>
<p>Then we can solve <span class="math inline">\(x\)</span> for a particular value of <span class="math inline">\(p\)</span>. For example, what value of <code>Cont4</code> will give a 75% probability of <code>Resp3.b</code> being 1, given your bestmod3.b of <code>Resp3.b ~ Cont4 + 1</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make my inverse predicting function that is specific to this model:</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>funInvPred <span class="ot">&lt;-</span> <span class="cf">function</span> (p, model) {</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  modLink <span class="ot">&lt;-</span> <span class="fu">family</span>(model)<span class="sc">$</span>linkfun <span class="co"># get the conversion (link) for the model</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">modLink</span>(p) <span class="sc">-</span> <span class="fu">coef</span>(model)[[<span class="st">"(Intercept)"</span>]]) <span class="sc">/</span> <span class="fu">coef</span>(model)[[<span class="st">"Cont4"</span>]] <span class="co"># calculate x from p</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the equation to estimate Cont4 when there is a 75% probability of Resp3.b being 1:</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>myInvPred <span class="ot">&lt;-</span> <span class="fu">funInvPred</span>(<span class="at">p =</span> <span class="fl">0.75</span>, <span class="at">model =</span> bestMod3.b) </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>myInvPred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85.18394</code></pre>
</div>
</div>
<p>The result is that you will have a 75% probability of <code>Resp3.b</code> being 1 if your <code>Cont4</code> is r round(myInvPred,1) units. Note that there is no error estimated here. Generalized linear models assume that there is no error in your predictors, so getting the error on your inverse prediction is tricky and beyond the scope of this handbook.</p>
<p>Let’s finish here by adding our inverse prediction to the plot:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="DSPPH_SM_Predicting_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="up-next" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="up-next"><span class="header-section-number">1.4</span> Up next</h2>
<p>You did it! You made it through all the steps of our Statistical Modelling Framework. Nice work!</p>
<p>Up next we will practice applying the framework to new examples, and learn how to <a href="DSPPH_SM_Communicating">communicate</a> the whole process in reports and papers.</p>


</section>
</section>


<p>Copyright 2025, DSP Taskforce</p><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>In a previous section, we had the quote “All models are wrong but some are useful” to emphasize that models are approximation of the real world. Well, we can also say that “all data are wrong, but models can make data useful” (a quote by Andy Pershing) to emphasize that models are also needed to make generalizations and predictions about the systems that we are studying.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>I realize that the term “prediction” and “predictor” can be confusing. Remember that another word for your model predictor is “covariate”.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>note that when you hand a GLM object to <code>predict()</code>, R actually uses a function called <code>predict.glm()</code>. This does not affect what you need to do; it is just good to know in case you need help with the function<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>recall that this is also called “logistic regression”<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>sometimes called <span class="math inline">\(LD_{25}\)</span> where LD is lethal dose<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>sometimes called the <span class="math inline">\(A_{50}\)</span><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Copyright 2025, DSP Taskforce</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>