<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Skills Portfolio Program - Reporting the explained deviance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data_skills_logo_2.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Skills Portfolio Program</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./intro.html" rel="" target="">
 <span class="menu-text">What is the DSP Program?</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./handbookIntro.html" rel="" target="">
 <span class="menu-text">The DSP Program Handbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./feedback.html" rel="" target="">
 <span class="menu-text">Feedback</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec_reportExplainedDeviance" id="toc-sec_reportExplainedDeviance" class="nav-link active" data-scroll-target="#sec_reportExplainedDeviance"><span class="header-section-number">1</span> Reporting how well your model explains your response</a>
  <ul class="collapse">
  <li><a href="#how-much-variation-deviance-in-your-response-is-explained-by-your-model" id="toc-how-much-variation-deviance-in-your-response-is-explained-by-your-model" class="nav-link" data-scroll-target="#how-much-variation-deviance-in-your-response-is-explained-by-your-model"><span class="header-section-number">1.1</span> how much variation (deviance) in your response is explained by your model</a></li>
  <li><a href="#how-important-is-each-of-your-predictors-in-explaining-that-variation" id="toc-how-important-is-each-of-your-predictors-in-explaining-that-variation" class="nav-link" data-scroll-target="#how-important-is-each-of-your-predictors-in-explaining-that-variation"><span class="header-section-number">1.2</span> how important is each of your predictors in explaining that variation</a></li>
  </ul></li>
  <li><a href="#back-to-reporting-main-page" id="toc-back-to-reporting-main-page" class="nav-link" data-scroll-target="#back-to-reporting-main-page"><span class="header-section-number">2</span> Back to Reporting main page</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reporting the explained deviance</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="sec_reportExplainedDeviance" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Reporting how well your model explains your response</h1>
<div class="alert alert-success">
<p>This section is similar regardless of your model structure (e.g.&nbsp;error distribution assumption). The examples below all assume a normal error distribution assumption but you can use the process presented here for models of any structure.</p>
</div>
<p>In this section you will report</p>
<ul>
<li><p>how much variation (deviance) in your response is explained by your model</p></li>
<li><p>how important each of your predictors is in explaining that deviance</p></li>
</ul>
<section id="how-much-variation-deviance-in-your-response-is-explained-by-your-model" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="how-much-variation-deviance-in-your-response-is-explained-by-your-model"><span class="header-section-number">1.1</span> how much variation (deviance) in your response is explained by your model</h2>
<p>If you will recall, your whole motivation for pursuing statistical modelling was to explain variation in your response. Thus, it is important that you quantify how much variation in your response you are able to explain by your model.</p>
<p>Note that <strong>we will discuss this as “explained deviance” rather than “explained variation”</strong>. This is because the term “variance” is associated with models where the error distribution assumption is normal, whereas deviance is a more universal term.</p>
<p>When you have a <strong>normal error distribution assumption and linear shape assumption</strong>, you can capture the amount of explained deviance simply by comparing the variation in your response (i.e.&nbsp;the starting variation <em>before</em> you fit your model - the null variation) vs.&nbsp;the variation in your model residuals (i.e.&nbsp;the remaining variation <em>after</em> you fit your model - the residual variation) as the <span class="math inline">\(R^2\)</span>:</p>
<p><span class="math inline">\(R^2 = 1 - \frac{residual variation}{null variation}\)</span></p>
<p>From this equation, you can see how, if your model is able to explain all the variation in the response, the residual variation will be zero, and <span class="math inline">\(R^2 = 1\)</span>. Alternatively, if the model explains no variation in the response the residual variation equals the null variation and <span class="math inline">\(R^2 = 0\)</span>.</p>
<p>For models with <strong>other error distribution and shape assumptions</strong>, you need another way of estimating the goodness of fit of your model. You can do this through estimating a pseudo <span class="math inline">\(R^2\)</span>.</p>
<p>There are many many different types of pseudo <span class="math inline">\(R^2\)</span>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> One useful pseudo <span class="math inline">\(R^2\)</span> is called the Likelihood Ratio <span class="math inline">\(R^2\)</span> or <span class="math inline">\(R^2_{LR}\)</span>. The <span class="math inline">\(R^2_{LR}\)</span> compares the likelihood of your best-specified model to the likelihood of the null model:</p>
<p><span class="math inline">\(R^2_{LR} = 1-exp(-\frac{2}{n}(log𝓛(model)-log𝓛(null)))\)</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of observations, <span class="math inline">\(log𝓛(model)\)</span> is the log-likelihood of your model, and <span class="math inline">\(log𝓛(null)\)</span> is the log-likelihood of the null model. The <span class="math inline">\(R^2_{LR}\)</span> is the type of pseudo <span class="math inline">\(R^2\)</span> that shows up in your <code>dredge()</code> output when you add <code>extra = "R^2"</code> to the <code>dredge()</code> call. You can calculate <span class="math inline">\(R^2_{LR}\)</span> by hand, read it from our <code>dredge()</code> output, or estimate it using <code>r.squaredLR()</code> from the MuMIn package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredLR</span>(bestMod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2644618
attr(,"adj.r.squared")
[1] 0.2646806</code></pre>
</div>
</div>
<p>Note here that two values of <span class="math inline">\(R^2_{LR}\)</span> are reported. The adjusted pseudo <span class="math inline">\(R^2\)</span> given here under <code>attr(,"adj.r.squared")</code> has been scaled so that <span class="math inline">\(R^2_{LR}\)</span> can reach a maximum of 1, similar to a regular <span class="math inline">\(R^2\)</span><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Let’s compare this to the traditional <span class="math inline">\(R^2\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">summary</span>(bestMod1)<span class="sc">$</span>deviance<span class="sc">/</span><span class="fu">summary</span>(bestMod1)<span class="sc">$</span>null.deviance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2644618</code></pre>
</div>
</div>
<p>Note that the two estimates are similar: One nice feature of the <span class="math inline">\(R^2_{LR}\)</span> is that it is equivalent to the regular <span class="math inline">\(R^2\)</span> when our model assumes a normal error distribution assumption and linear shape assumption, so you can use <span class="math inline">\(R^2_{LR}\)</span> for a wide range of models.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Aside: what is a *good* $R^2$?">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aside: what is a <em>good</em> <span class="math inline">\(R^2\)</span>?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><img src="./goodR2.png" align="right" width="300px"></p>
<p>Recall that your goal in hypothesis testing is to explain the variation in your response - preferably as much variation as possible! So it is natural to hope for a high <code>R^2</code> but this is a trap: the results of your hypothesis testing<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> are valuable whether you are able to explain 3% or 93% of the variation in your response. Remember:</p>
<ul>
<li><p>You are progressing science either way - helping the field learn about mechanisms and design future experiments.</p></li>
<li><p>Remaining unexplained variation points to potential limitations in measuring predictor effects and/or other predictors (not in your model) that may play a role.</p></li>
</ul>
<p>For context, here is a plot of <code>R^2</code> values from a meta-analysis of biology studies:</p>
<p><br clear="right"></p>
</div>
</div>
</div>
</section>
<section id="how-important-is-each-of-your-predictors-in-explaining-that-variation" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="how-important-is-each-of-your-predictors-in-explaining-that-variation"><span class="header-section-number">1.2</span> how important is each of your predictors in explaining that variation</h2>
<p>When you have more than one predictor in your model, you may also want to report how relatively important each predictor is to explaining deviance in your response. This is also called “partitioning the explained deviance” to the predictors or “variance decomposition”.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Aside: what we won't be doing">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aside: what we won’t be doing
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To get an estimate of how much deviance in your response one particular predictor explains, you may be tempted to compute the explained deviance (<span class="math inline">\(R^2\)</span>) estimates of models fit to data with and without that particular predictor. Let us try with our Example 4:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dredgeOut4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: glm(formula = Resp4 ~ Cat5 + Num6 + Cat5:Num6 + 1, family = gaussian(link = "identity"), 
    data = myDat4)
---
Model selection table 
   (Int) Ct5       Nm6 Ct5:Nm6    R^2 df   logLik  AICc  delta weight
8  98.35   + -0.002931       + 0.8557  7 -234.930 485.1   0.00      1
4  92.25   +  0.009650         0.8166  5 -246.915 504.5  19.39      0
2  96.93   +                   0.7923  4 -253.133 514.7  29.61      0
3  94.92      0.017780         0.0848  3 -327.278 660.8 175.73      0
1 104.00                       0.0000  2 -331.708 667.5 182.46      0
Models ranked by AICc(x) </code></pre>
</div>
</div>
<p>If you want to get an estimate as to how much response deviance the <code>Num6</code> predictor explains, you might compare the <span class="math inline">\(R^2\)</span> of a model with and without the <code>Num6</code> predictor.</p>
<p>Let’s compare model #4 (that includes <code>Num6</code>) and model #2 (that does NOT include <code>Num6</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>R2.mod4 <span class="ot">&lt;-</span> (dredgeOut4<span class="sc">$</span><span class="st">`</span><span class="at">R^2</span><span class="st">`</span>[<span class="dv">2</span>]) <span class="co"># model #4 is the second row in dredgeOut4</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>R2.mod2 <span class="ot">&lt;-</span> (dredgeOut4<span class="sc">$</span><span class="st">`</span><span class="at">R^2</span><span class="st">`</span>[<span class="dv">3</span>]) <span class="co"># model #2 is the third row in dredgeOut4</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>diffR2 <span class="ot">&lt;-</span> R2.mod4 <span class="sc">-</span> R2.mod2 <span class="co"># find estimated contribution of Cont to explained deviance</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>diffR2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02429225</code></pre>
</div>
</div>
<p>So it looks like 2.4% of the variability in <code>Resp4</code> is explained by <code>Num6</code>.</p>
<p>But what if instead you chose to compare model #3 (that includes <code>Num6</code>) and model #1 (that does NOT include <code>Num6</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>R2.mod3 <span class="ot">&lt;-</span> (dredgeOut4<span class="sc">$</span><span class="st">`</span><span class="at">R^2</span><span class="st">`</span>[<span class="dv">4</span>]) <span class="co"># model #3 is the fourth row in dredgeOut4</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>R2.mod1 <span class="ot">&lt;-</span> (dredgeOut4<span class="sc">$</span><span class="st">`</span><span class="at">R^2</span><span class="st">`</span>[<span class="dv">5</span>]) <span class="co"># model #1 is the fifth row in dredgeOut4</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>diffR2 <span class="ot">&lt;-</span> R2.mod3 <span class="sc">-</span> R2.mod1 <span class="co"># find estimated contribution of Cont to explained deviance</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>diffR2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08480009</code></pre>
</div>
</div>
<p>Now it looks like 8.5% of the variability in <code>Resp4</code> is explained by <code>Num6</code>! Quite a different answer! Your estimates of the contribution of <code>Num6</code> to explaining the response deviation do not agree because of collinearity among your predictors - more on this in the section on <a href="./DSPPH_SM_ModelValidation.html">Model Validation</a>.</p>
</div>
</div>
</div>
<p>There are a few options you can use to get a robust estimate of how much each predictor is contributing to explained deviance in your response.</p>
<p>One option for partitioning the explained deviance when you have collinearity among your predictors is hierarchical partitioning. Hierarchical partitioning estimates the average independent contribution of each predictor to the total explained variance by considering all models in the candidate model set<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. This method is beyond the scope of the course but see the <a href="https://cran.r-project.org/web/packages/rdacca.hp/index.html">rdacca.hp package</a> for an example of how to do this.</p>
<p>Another method (<strong>that we will be using</strong>) for estimating the importance of each term (predictor or interaction) in your model is by looking at the candidate model set ranking made by <code>dredge()</code>. Here you can measure the importance of a predictor by summing up the Akaike weights for any model that includes a particular predictor. The Akaike weight of a model compares the likelihood of the model scaled to the total likelihood of all the models in the candidate model set. The sum of Akaike weights for models including a particular predictor tells you how important the predictor is in explaining the deviance in your response. You can calculate the sum of Akaike weights directly with the <code>sw()</code> function in the MuMIn package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sw</span>(dredgeOut4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Cat5 Num6 Cat5:Num6
Sum of weights:      1    1    1        
N containing models: 3    3    1        </code></pre>
</div>
</div>
<p>Here we can see that all model terms (the predictors <code>Cat5</code> and <code>Num6</code> as well as the interaction) are equally important in explaining the deviance in <code>Resp4</code> (they appear in all models that have any Akaike weight).</p>
<p>Let’s look at these two steps</p>
<ul>
<li><p>how much deviance in your response is explained by your model</p></li>
<li><p>how important each of your predictors is in explaining that deviance</p></li>
</ul>
<p>with our examples:</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Example 1: Resp1 ~ Cat1 + 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 1: Resp1 ~ Cat1 + 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<section id="example-1-resp1-cat1-1" class="level4 callout-body-container callout-body">
<h4 class="anchored" data-anchor-id="example-1-resp1-cat1-1">Example 1: Resp1 ~ Cat1 + 1</h4>
<ul>
<li>how much deviance in your response is explained by your model</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> <span class="fu">r.squaredLR</span>(bestMod1)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>R2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2644618
attr(,"adj.r.squared")
[1] 0.2646806</code></pre>
</div>
</div>
<p>The best-specified model explains 26.4% of the deviance in <code>Resp1</code>.</p>
<ul>
<li>how important each of your predictors is in explaining that deviance</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dredgeOut2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: glm(formula = Resp2 ~ Cat2 + Cat3 + Cat2:Cat3, family = gaussian(link = "identity"), 
    data = myDat2)
---
Model selection table 
  (Int) Ct2 Ct3 Ct2:Ct3     R^2 df   logLik   AICc delta weight
8 364.9   +   +       + 0.69800 13 -553.634 1137.5  0.00  0.964
4 354.9   +   +         0.62540  7 -564.419 1144.1  6.55  0.036
2 388.5   +             0.55300  5 -573.243 1157.1 19.63  0.000
1 348.3                 0.00000  2 -613.508 1231.1 93.64  0.000
3 331.1       +         0.03933  4 -611.502 1231.4 93.92  0.000
Models ranked by AICc(x) </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sw</span>(dredgeOut1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Cat1
Sum of weights:      1   
N containing models: 1   </code></pre>
</div>
</div>
<p>With Example 1, you have only one predictor (<code>Cat1</code>) and so this predictor is responsible for explaining all of the variability in your response (<code>Resp1</code>). You can see that it appears in all models with any weight with your <code>sw()</code> function from the MuMIn package.</p>
</section>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Example 2: Resp2 ~ Cat2 + Cat3 + Cat2:Cat3 + 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 2: Resp2 ~ Cat2 + Cat3 + Cat2:Cat3 + 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<section id="example-2-resp2-cat2-cat3-cat2cat3-1" class="level4 callout-body-container callout-body">
<h4 class="anchored" data-anchor-id="example-2-resp2-cat2-cat3-cat2cat3-1">Example 2: Resp2 ~ Cat2 + Cat3 + Cat2:Cat3 + 1</h4>
<ul>
<li>how much deviance in your response is explained by your model</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> <span class="fu">r.squaredLR</span>(bestMod2)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>R2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6980474
attr(,"adj.r.squared")
[1] 0.6980507</code></pre>
</div>
</div>
<p>The best-specified model explains 69.8% of the deviance in <code>Resp2</code>.</p>
<ul>
<li>how important each of your predictors is in explaining that deviance</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dredgeOut2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: glm(formula = Resp2 ~ Cat2 + Cat3 + Cat2:Cat3, family = gaussian(link = "identity"), 
    data = myDat2)
---
Model selection table 
  (Int) Ct2 Ct3 Ct2:Ct3     R^2 df   logLik   AICc delta weight
8 364.9   +   +       + 0.69800 13 -553.634 1137.5  0.00  0.964
4 354.9   +   +         0.62540  7 -564.419 1144.1  6.55  0.036
2 388.5   +             0.55300  5 -573.243 1157.1 19.63  0.000
1 348.3                 0.00000  2 -613.508 1231.1 93.64  0.000
3 331.1       +         0.03933  4 -611.502 1231.4 93.92  0.000
Models ranked by AICc(x) </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sw</span>(dredgeOut2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Cat2 Cat3 Cat2:Cat3
Sum of weights:      1.00 1.00 0.96     
N containing models:    3    3    1     </code></pre>
</div>
</div>
<p>Here you can see that <code>Cat2</code> and <code>Cat3</code> are equally important in explaining the deviance in <code>Resp2</code> (they appear in all models that have any Akaike weight), while the interaction term between <code>Cat2</code> and <code>Cat3</code> is less important (only appearing in one model with Akaike weight, though this is the top model).</p>
</section>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Example 3: Resp3 ~ Num4 + 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 3: Resp3 ~ Num4 + 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<section id="example-3-resp3-num4-1" class="level4 callout-body-container callout-body">
<h4 class="anchored" data-anchor-id="example-3-resp3-num4-1">Example 3: Resp3 ~ Num4 + 1</h4>
<ul>
<li>how much deviance in your response is explained by your model</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> <span class="fu">r.squaredLR</span>(bestMod3)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>R2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.764852
attr(,"adj.r.squared")
[1] 0.764852</code></pre>
</div>
</div>
<p>The best-specified model explains 76.5% of the deviance in <code>Resp3</code>.</p>
<ul>
<li>how important each of your predictors is in explaining that deviance</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dredgeOut3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: glm(formula = Resp3 ~ Num4 + 1, family = gaussian(link = "identity"), 
    data = myDat3)
---
Model selection table 
  (Intrc)  Num4 df   logLik   AICc  delta weight
2  -226.9 260.1  3 -811.080 1628.4   0.00      1
1  2358.0        2 -883.457 1771.0 142.63      0
Models ranked by AICc(x) </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sw</span>(dredgeOut3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Num4
Sum of weights:      1   
N containing models: 1   </code></pre>
</div>
</div>
<p>With Example 3, you have only one predictor (<code>Num6</code>) and so this predictor is responsible for explaining all of the variability in your response (<code>Resp3</code>). You can see that it appears in all models with any weight with your <code>sw()</code> function from the MuMIn package.</p>
</section>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Example 4: Resp4 ~ Cat5 + Num6 + Cat5:Num6 + 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 4: Resp4 ~ Cat5 + Num6 + Cat5:Num6 + 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<section id="example-4-resp4-cat5-num6-cat5num6-1" class="level4 callout-body-container callout-body">
<h4 class="anchored" data-anchor-id="example-4-resp4-cat5-num6-cat5num6-1">Example 4: Resp4 ~ Cat5 + Num6 + Cat5:Num6 + 1</h4>
<ul>
<li>how much deviance in your response is explained by your model</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> <span class="fu">r.squaredLR</span>(bestMod4)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>R2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.855657
attr(,"adj.r.squared")
[1] 0.8567834</code></pre>
</div>
</div>
<p>The best-specified model explains 85.6% of the deviance in <code>Resp2</code>.</p>
<ul>
<li>how important each of your predictors is in explaining that deviance</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>dredgeOut4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: glm(formula = Resp4 ~ Cat5 + Num6 + Cat5:Num6 + 1, family = gaussian(link = "identity"), 
    data = myDat4)
---
Model selection table 
   (Int) Ct5       Nm6 Ct5:Nm6    R^2 df   logLik  AICc  delta weight
8  98.35   + -0.002931       + 0.8557  7 -234.930 485.1   0.00      1
4  92.25   +  0.009650         0.8166  5 -246.915 504.5  19.39      0
2  96.93   +                   0.7923  4 -253.133 514.7  29.61      0
3  94.92      0.017780         0.0848  3 -327.278 660.8 175.73      0
1 104.00                       0.0000  2 -331.708 667.5 182.46      0
Models ranked by AICc(x) </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sw</span>(dredgeOut4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Cat5 Num6 Cat5:Num6
Sum of weights:      1    1    1        
N containing models: 3    3    1        </code></pre>
</div>
</div>
<p>Here you can see that <code>Cat5</code>, <code>Num6</code> and the interaction <code>Cat5:Num6</code> are all equally important in explaining the deviance in <code>Resp4</code> (they appear in all models that have any Akaike weight).</p>
</section>
</div>
</div>
</section>
</section>
<section id="back-to-reporting-main-page" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> <a href="./DSPPH_SM_Reporting.html">Back to Reporting main page</a></h1>


</section>


<a href="https://neuheimerlab.github.io/DSPPHandbook/">Data Skills Portfolio Program </a><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>check the <a href="https://cran.r-project.org/web/packages/effectsize/vignettes/interpret.html">rr2 package</a> for many different options<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>this is called the Nagelkerke’s modified statistic - see <code>?r.squaredLR</code> for more information<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>when done in a robust fashion<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>i.e.&nbsp;in the <code>dredge()</code> output<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>